owner: ICodeWorld-Inc
repo: status-pages

sites:
  - name: web-runtime
    url: https://web-runtime-release.easybits.cn/

status-website:
  cname: status.easybits.cn
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: meland status
  introTitle: "Meland.ai status pages"
  introMessage: Here you can see the operation of all services of meland.ai
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO